# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
    - run: arm-none-eabi-gcc --version
    
    - name: Build
      run: |
        rm -rf build
        mkdir -p build
        cd build
        cmake ..
        make -j$(nproc)
